<?php

namespace Database\Seeders;

use App\Models\Club;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class ClubsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $clubs = [
            "Admiral Callaghan Society",
            "Advancing Renewable Energy",
            "AI Club",
            "Aid for Filipino Student Education",
            "Aneurysm Awareness Club",
            "Anime Club",
            "Armenian Club",
            "Arrupe Social Justice Council",
            "Art Apparel and Accessories Club",
            "Art History Club",
            "Art Therapy Club",
            "ASL Club",
            "Baking Club",
            "Beach Clean Up Club",
            "Beach Volleyball Club",
            "Bioethics/Ethics Club",
            "Black Scholars",
            "Block Club",
            "Book Lovers",
            "Bowling Club",
            "Brady Therapeutic Riding Club",
            "Bring Change to Mind",
            "Budding Penships",
            "California Scholarship Federation - CSF",
            "Camp ReCreation",
            "Cancer Awareness and Support Club",
            "Canine Companions - SI Student Chapter",
            "Cardiac Health Awareness Club",
            "CCSC PK-5 Tutoring Club",
            "CEC - Clean Energy Club",
            "Chess Club",
            "Chinese Culture Club",
            "Cinema Club",
            "Collective Impact",
            "Community Service Club",
            "Competitive Math Club - CMC",
            "Computer Science Club",
            "Cornhole Club",
            "Crew",
            "Crocheting for the Community",
            "Daraja Club",
            "Detective/Forensic Science Club",
            "DIF - National System for Integral Family Development",
            "Digital Currency Club",
            "Disability Alliance Group",
            "Disney Club",
            "Emerging Markets Club",
            "Empower Her Health Club",
            "Endangered Animal Welfare",
            "Entrepreneurs Club",
            "Epilepsy Awareness Club",
            "eSports",
            "Fashion Club",
            "Feed Bright Futures",
            "Female Athletic Empowerment Club",
            "Film Club",
            "Finance Club",
            "Fishing Club",
            "Food Science Club",
            "French Club",
            "FSA Play Club",
            "Future Business Leaders Club",
            "Gaming Club",
            "Gardening Club",
            "G.E.A.R - Gender Equality and Rights Club",
            "German Club",
            "Girls in Journalism",
            "Girls in STEM Pathways",
            "Girl Scouts of Northern California",
            "Girls Who Code",
            "Girls Who Lift",
            "Global Readers",
            "Golden Gate Robotics Club",
            "Golf Club",
            "Green Team",
            "Grill Club",
            "HEAL Club - Healthy Eating and Active Living",
            "He(art)",
            "Help 4 Health",
            "Hope for Homes",
            "InSide SI Newspaper",
            "Irish Club",
            "Italian Club",
            "Junior Classical League - JCL",
            "KATS Radio",
            "Key Club",
            "Kidney Club",
            "Korean Culture Club",
            "LeaderOURship",
            "Lending a Paw",
            "Life Skills for Resume Building, Interviewing, & Developing Linked In",
            "Magic the Gathering Club",
            "Marine Conservation Club",
            "Martial Arts Club",
            "Medcats",
            "Mock Trial",
            "Model United Nations",
            "Mountain Biking Club",
            "Munching Grounds",
            "Music for Others",
            "Music Production Club",
            "NB3 - Notah Begay the Third",
            "Octonauts Ocean Club",
            "Open Water Swim Club",
            "Pass n Go",
            "Pet Nation",
            "Pickleball Club",
            "Ping Pong Club",
            "Poker Club",
            "Polyglot Club",
            "Polynesian Dance Club",
            "Psychology Club",
            "Rugby",
            "Sailing",
            "Senior Tech Club",
            "Service Club",
            "SI Athletic Pride",
            "SI Supporters of Doctors Without Borders - DWB",
            "SI T1D Club",
            "SI Unicef Club",
            "SITV",
            "Skateboarding Club",
            "Ski and Snowboard Club",
            "SKY - Strings and Keys for Youth",
            "South Asian Club",
            "Space Club",
            "Speech and Debate",
            "Spoken Word Collective",
            "Sports Analytics",
            "Sports Medicine",
            "Sports Network",
            "St. Ignatius Water Project",
            "Stand By Me",
            "STEM Club",
            "Students Against Sexual Harassment",
            "Surf Club",
            "TEDxSI",
            "The Apogee Report",
            "The Disaster Project",
            "The Filipino Culture Club",
            "The Quill Literary Magazine",
            "The Waterski and Wakeboard Club",
            "There With Care",
            "Thursday Morning Comfort Run",
            "Tutoring by the Bay",
            "Ultimate Frisbee",
            "White Anti-Racist Alliance",
            "Wildcat Careers",
            "Wildcat Nation",
            "Wildcast Podcast Club",
            "Women in Business",
            "Women's Health Advocacy Club",
            "Yearbook - The Ignatian",
            "Young Democrats",
            "Youth-for-Youth Refugee Outreach",
            "Youth Leaders in Lit"
        ];

        foreach ($clubs as $clubName) {
            Club::firstOrCreate(['name' => $clubName]);
        }
    
    }
}
